version: '3.9'

services:
  customerapi:
    build:
      context: .
      dockerfile: "CustomerApi/Dockerfile"
    ports:
      - 8000:80
  orderapi:
    build:
      context: .
      dockerfile: "OrderApi/Dockerfile"
    ports:
      - 8001:80
    depends_on:
      - seq
      - zipkin
  productapi:
    build:
      context: .
      dockerfile: "ProductApi/Dockerfile"
    ports:
      - 8002:80
  emailservice:
    build:
      context: .
      dockerfile: "EmailService/Dockerfile"
    ports:
      - 8003:80
    depends_on:
      - customerapi
      - featurehub

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - onlineretailer_partial_data:/data
    environment:
      - ACCEPT_EULA=Y
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data

volumes:
  onlineretailer_partial_data:
  zipkin_data:
  featurehub-h2-data: