version: '3.9'

services:
# orderapi + dapr sidecar
  orderapi:
    build:
      context: .
      dockerfile: "OrderApi/Dockerfile"
    image: onlineretailer_partial-orderapi
    depends_on:
      - seq
    ports:
      - 8000:80

  orderapi-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "orderapi", "-app-port", "80", "-components-path", "/dapr/components", "-log-level", "debug", "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - orderapi
    network_mode: "service:orderapi"

#customerapi + dapr sidecar
  customerapi:
    build:
      context: .
      dockerfile: "CustomerApi/Dockerfile"
    image: onlineretailer_partial-customerapi
    ports:
      - 8001:80

  customerapi-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "customerapi", "-app-port", "80", "-components-path", "/dapr/components", "-log-level", "debug", "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - customerapi
    network_mode: "service:customerapi"
  
  #productapi + dapr sidecar
  productapi:
    build:
      context: .
      dockerfile: "ProductApi/Dockerfile"
    image: onlineretailer_partial-productapi
    ports:
      - 8002:80

  product-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "productapi", "-app-port", "80", "-components-path", "/dapr/components", "-log-level", "debug", "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - productapi
    network_mode: "service:productapi"

  #emailapi + dapr sidecar
  emailservice:
    build:
      context: .
      dockerfile: "EmailService/Dockerfile"
    image: onlineretailer_partial-emailservice
    ports:
      - 8003:80
    depends_on:
      - customerapi
      - featurehub

  email-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "emailservice", "-app-port", "80", "-components-path", "/dapr/components", "-log-level", "debug", "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - productapi
    network_mode: "service:emailservice"

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - onlineretailer_partial_data:/data
    environment:
      - ACCEPT_EULA=Y
      
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data

volumes:
  onlineretailer_partial_data:
  zipkin_data:
  featurehub-h2-data: