version: '3.9'

services:
  customerapi:
    build:
      context: .
      dockerfile: "CustomerApi/Dockerfile"
    image: annechristensen1995/onlineretailer_partial-customerapi:$BUILD_NUMBER

  customerapi-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "customerapi", "-app-port", "8000", "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - customerapi
    ports:
      - 8000:80

  orderapi:
    build:
      context: .
      dockerfile: "OrderApi/Dockerfile"
    image: annechristensen1995/onlineretailer_partial-orderapi:$BUILD_NUMBER
    depends_on:
      - seq

  orderapi-dapr:
    image: daprio/daprd:edge
    command: ["./daprd", "-app-id", "orderapi", "-app-port", "8001", "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - orderapi
    ports:
      - 8001:80
  
  productapi:
    build:
      context: .
      dockerfile: "ProductApi/Dockerfile"
    image: annechristensen1995/onlineretailer_partial-productapi:$BUILD_NUMBER
    ports:
      - 8002:80
  emailservice:
    build:
      context: .
      dockerfile: "EmailService/Dockerfile"
    image: annechristensen1995/onlineretailer_partial-emailservice:$BUILD_NUMBER
    ports:
      - 8003:80
    depends_on:
      - customerapi
      - featurehub

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - onlineretailer_partial_data:/data
    environment:
      - ACCEPT_EULA=Y
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data

  redis:
    image: "redis:alpine"
    hostname: redisstate
    ports:
      - 6379:6379

volumes:
  onlineretailer_partial_data:
  zipkin_data:
  featurehub-h2-data: