version: '3.9'

services:
  customerapi:
    build:
      context: .
      dockerfile: "CustomerApi/Dockerfile"
    ports:
      - 8000:80
    deploy:
     replicas: 1
  orderapi:
    build:
      context: .
      dockerfile: "OrderApi/Dockerfile"
    ports:
      - 8001:80
    depends_on:
      - customerapi
      - productapi
    deploy:
      replicas: 1
  productapi:
    build:
      context: .
      dockerfile: "ProductApi/Dockerfile"
    ports:
      - 8002:80
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"