apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
scopes:
  - emailservice
  - orderapi
  - customerapi
  - productapi
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqps://djgafrdt:N069t12xrumLFnbNr-ZRoCZFtvKQGe7D@sparrow.rmq.cloudamqp.com/djgafrdt
  - name: protocol
    value: amqps
  